PBL3_MVC/Areas/Admin/Controllers/BusesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PBL3_MVC.Data;
using PBL3_MVC.Data.Tables;

namespace PBL3_MVC.Areas.Admin.Controllers
{
    public class BusesController : Controller
    {
        private Db db = new Db();

        // GET: Admin/Buses
        public ActionResult Index()
        {
            var buses = db.Buses.Include(b => b.BusStation);
            return View(buses.ToList());
        }

        // GET: Admin/Buses/Create
        public ActionResult Create()
        {
            ViewBag.BusStationID = new SelectList(db.BusStations, "BusStationID", "Name");
            return View();
        }

        // POST: Admin/Buses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BusID,BusStationID,BusName,BusNumber,RegisterPerson,Driver,LicenseDate,NumberOfSeats")] Bus bus)
        {
            if (DateTime.Now < bus.LicenseDate)
            {
                ModelState.AddModelError("", "Ngày cấp phép không phù hợp!!");
            }
            if (bus.NumberOfSeats <= 0)
            {
                ModelState.AddModelError("", "Số lượng ghế không thể nhỏ hơn 0!!");
            }
            var checkName = db.Buses.FirstOrDefault(b => b.BusNumber == bus.BusNumber);
            if (checkName == null)
            {
                if (ModelState.IsValid)
                {
                    bus.RegDate = DateTime.Now.Date;
                    db.Buses.Add(bus);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            else
            {
                ModelState.AddModelError("", "Biển số xe đã tồn tại!!");
            }

            ViewBag.BusStationID = new SelectList(db.BusStations, "BusStationID", "Name", bus.BusStationID);
            return View(bus);
        }

        // GET: Admin/Buses/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bus bus = db.Buses.Find(id);
            if (bus == null)
            {
                return HttpNotFound();
            }
            ViewBag.BusStationID = new SelectList(db.BusStations, "BusStationID", "Name", bus.BusStationID);
            return View(bus);
        }

        // POST: Admin/Buses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Bus bus)
        {
            if (bus.NumberOfSeats <= 0)
            {
                ModelState.AddModelError("", "Số lượng ghế không thể nhỏ hơn 0!!");
                return View(bus);
            }
            var checkName = db.Buses.FirstOrDefault(b => b.BusNumber == bus.BusNumber && b.BusID != bus.BusID);
            if (checkName == null)
            {
                if (ModelState.IsValid)
                {
                    db.Entry(bus).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            else
            {
                ModelState.AddModelError("", "Tên xe đã tồn tại!!");
            }

            ViewBag.BusStationID = new SelectList(db.BusStations, "BusStationID", "Name", bus.BusStationID);
            return View(bus);
        }

        // GET: Admin/Buses/Delete/5
        public ActionResult Delete(int? id)
        {
            Bus bus = db.Buses.Find(id);
            db.Buses.Remove(bus);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PBL3_MVC/Areas/BusStationArea/Controllers/BusesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PBL3_MVC.Data;
using PBL3_MVC.Data.Tables;

namespace PBL3_MVC.Areas.BusStationArea.Controllers
{
    public class BusesController : Controller
    {
        private Db db = new Db();

        // GET: BusStation/Buses
        public ActionResult Index()
        {
            var userSession = Session["User"] as PBL3_MVC.Data.Tables.Account;
            var buses = db.Buses.Include(b => b.BusStation).Where(b => b.BusStation.Account.UserName == userSession.UserName);
            return View(buses.ToList());
        }

        // GET: BusStation/Buses/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: BusStation/Buses/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BusID,BusName,BusNumber,RegisterPerson,Driver,LicenseDate,NumberOfSeats")] Bus bus)
        {
            if (DateTime.Now < bus.LicenseDate)
            {
                ModelState.AddModelError("", "Ngày cấp phép không phù hợp!!");
            }
            if (bus.NumberOfSeats <= 0)
            {
                ModelState.AddModelError("", "Số lượng ghế không thể nhỏ hơn 0!!");
            }
            var checkName = db.Buses.FirstOrDefault(b => b.BusNumber == bus.BusNumber);
            if (checkName == null)
            {
                if (ModelState.IsValid)
                {
                    var userSession = Session["User"] as PBL3_MVC.Data.Tables.Account;

                    bus.RegDate = DateTime.Now.Date;
                    bus.BusStationID = userSession.AccountID;
                    db.Buses.Add(bus);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            else
            {
                ModelState.AddModelError("", "Biển số xe đã tồn tại!!");
            }

            ViewBag.BusStationID = new SelectList(db.BusStations, "BusStationID", "Name", bus.BusStationID);
            return View(bus);
        }

        // GET: Admin/Buses/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bus bus = db.Buses.Find(id);
            if (bus == null)
            {
                return HttpNotFound();
            }
            ViewBag.BusStationID = new SelectList(db.BusStations, "BusStationID", "Name", bus.BusStationID);
            return View(bus);
        }

        // POST: Admin/Buses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Bus bus)
        {
            if (bus.NumberOfSeats <= 0)
            {
                ModelState.AddModelError("", "Số lượng ghế không thể nhỏ hơn 0!!");
                return View(bus);
            }
            var checkName = db.Buses.FirstOrDefault(b => b.BusNumber == bus.BusNumber && b.BusID != bus.BusID);
            if (checkName == null)
            {
                if (ModelState.IsValid)
                {
                    db.Entry(bus).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            else
            {
                ModelState.AddModelError("", "Tên xe đã tồn tại!!");
            }

            ViewBag.BusStationID = new SelectList(db.BusStations, "BusStationID", "Name", bus.BusStationID);
            return View(bus);
        }

        // GET: Admin/Buses/Delete/5
        public ActionResult Delete(int? id)
        {
            Bus bus = db.Buses.Find(id);
            db.Buses.Remove(bus);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PBL3_MVC/Areas/BusStationArea/Views/Buses/Create.cshtml
@model PBL3_MVC.Data.Tables.Bus

@{
    ViewBag.Title = "Thêm Xe";
    Layout = "~/Areas/BusStationArea/Views/Shared/_BusStationLayout.cshtml";
}

<h2>Thêm Xe</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.BusName, "Tên xe", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BusName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BusName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BusNumber, "Biển số xe", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BusNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BusNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RegisterPerson, "Người đăng ký", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RegisterPerson, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RegisterPerson, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Driver, "Tài xế", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Driver, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Driver, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LicenseDate, "Ngày cấp", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LicenseDate, new { htmlAttributes = new { @class = "form-control datetimepicker" } })
                @Html.ValidationMessageFor(model => model.LicenseDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumberOfSeats, "Số lượng ghế", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumberOfSeats, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumberOfSeats, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Tạo xe mới" class="btn btn-success btn-default" style="margin:15px" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Trở lại danh sách Xe", "Index")
</div>

<link href="~/Content/jquery.datetimepicker.css" rel="stylesheet" />
@section scripts{
    <script src="~/Scripts/jquery.datetimepicker.js"></script>
    <script>
        $(function () {
            $(".datetimepicker").datetimepicker(
                {
                    format: 'Y/m/d'
                });
        });
    </script>
}

PBL3_MVC/Areas/BusStationArea/Views/Buses/Edit.cshtml
@model PBL3_MVC.Data.Tables.Bus

@{
    ViewBag.Title = "Chỉnh sửa Xe";
    Layout = "~/Areas/BusStationArea/Views/Shared/_BusStationLayout.cshtml";
}

<h2>Chỉnh sửa Xe</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.BusID)
        @Html.HiddenFor(model => model.BusStationID)
        @Html.HiddenFor(model => model.BusNumber)
        @Html.HiddenFor(model => model.RegisterPerson)
        @Html.HiddenFor(model => model.RegDate)
        @Html.HiddenFor(model => model.LicenseDate)
        @Html.HiddenFor(model => model.NumberOfSeats)

        <div class="form-group">
            @Html.LabelFor(model => model.BusName, "Tên xe", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BusName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BusName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Driver, "Tài xế", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Driver, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Driver, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-success btn-default" style="margin:15px" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Trở lại danh sách xe", "Index")
</div>

<link href="~/Content/jquery.datetimepicker.css" rel="stylesheet" />
@section scripts{
    <script src="~/Scripts/jquery.datetimepicker.js"></script>
    <script>
        $(function () {
            $(".datetimepicker").datetimepicker(
                {
                    format: 'Y/m/d'
                });
        });
    </script>
}

PBL3_MVC/Areas/BusStationArea/Views/Buses/Index.cshtml
@model IEnumerable<PBL3_MVC.Data.Tables.Bus>

@{
    ViewBag.Title = "Quản lý Xe";
    Layout = "~/Areas/BusStationArea/Views/Shared/_BusStationLayout.cshtml";
}

<h2>Quản lý Xe</h2>

<p>
    @Html.ActionLink("Thêm xe mới", "Create", "Buses", new { area = "BusStationArea" }, new { @class = "btn btn-success" })
</p>
<table class="table">
    <tr>
        <th>
            Tên xe
        </th>
        <th>
            Biển số xe
        </th>
        <th>
            Người đăng ký
        </th>
        <th>
            Tài xế
        </th>
        <th>
            Ngày cấp
        </th>
        <th>
            Ngày đăng ký
        </th>
        <th>
            Số lượng ghế
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.BusName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BusNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RegisterPerson)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Driver)
            </td>
            <td>
                @item.LicenseDate.ToString("yyyy/MM/dd")
            </td>
            <td>
                @item.RegDate.ToString("yyyy/MM/dd")
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumberOfSeats)
            </td>
            <td>
                @Html.ActionLink("Chỉnh sửa", "Edit", new { id = item.BusID }) |
                @Html.ActionLink("Xóa", "Delete", new { id = item.BusID }, new { onclick = "return confirm('Bạn có chắc chắn muốn xóa không?');" })
            </td>
        </tr>
    }

</table>