PBL3_MVC/Areas/Admin/Controllers/RoutesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PBL3_MVC.Data;
using PBL3_MVC.Data.Tables;

namespace PBL3_MVC.Areas.Admin.Controllers
{
    public class RoutesController : Controller
    {
        private Db db = new Db();

        // GET: Admin/Routes
        public ActionResult Index()
        {
            return View(db.Routes.ToList());
        }

        // GET: Admin/Routes/Create
        public ActionResult Create()
        {
            ViewBag.DepartureID = new SelectList(db.Locations, "LocationID", "LocationName");
            ViewBag.DestinationID = new SelectList(db.Locations, "LocationID", "LocationName");
            return View();
        }

        // POST: Admin/Routes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "RouteID,RouteName,DepartureID,DestinationID")] Route route)
        {
            var checkName = db.Routes.FirstOrDefault(b => b.RouteName == route.RouteName);
            if (checkName == null)
            {
                if (ModelState.IsValid)
                {
                    db.Routes.Add(route);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            else
            {
                ModelState.AddModelError("", "Tên tuyến đường đã tồn tại!!");
            }

            return View(route);
        }

        // GET: Admin/Routes/Edit/5
        public ActionResult Edit(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Route route = db.Routes.Find(id);
            if (route == null)
            {
                return HttpNotFound();
            }
            ViewBag.DepartureID = new SelectList(db.Locations, "LocationID", "LocationName", route.DepartureID);
            ViewBag.DestinationID = new SelectList(db.Locations, "LocationID", "LocationName", route.DestinationID);
            return View(route);
        }

        // POST: Admin/Routes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "RouteID,RouteName,DepartureID,DestinationID")] Route route)
        {
            var checkName = db.Routes.FirstOrDefault(b => b.RouteName == route.RouteName && b.RouteID != route.RouteID);
            if (checkName == null)
            {
                if (ModelState.IsValid)
                {
                    db.Entry(route).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            else
            {
                ModelState.AddModelError("", "Tên tuyến đường đã tồn tại!!");
            }
            ViewBag.DepartureID = new SelectList(db.Locations, "LocationID", "LocationName", route.DepartureID);
            ViewBag.DestinationID = new SelectList(db.Locations, "LocationID", "LocationName", route.DestinationID);
            return View(route);
        }

        // GET: Admin/Routes/Delete/5
        public ActionResult Delete(int id)
        {
            Route route = db.Routes.Find(id);
            db.Routes.Remove(route);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PBL3_MVC/Areas/BusStationArea/Controllers/RoutesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PBL3_MVC.Data;
using PBL3_MVC.Data.Tables;

namespace PBL3_MVC.Areas.BusStationArea.Controllers
{
    public class RoutesController : Controller
    {
        private Db db = new Db();

        // GET: BusStationArea/Routes
        public ActionResult Index()
        {
            return View(db.Routes.ToList());
        }

        //// GET: BusStationArea/Routes/Create
        //public ActionResult Create()
        //{
        //    return View();
        //}

        //// POST: BusStationArea/Routes/Create
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "RouteID,RouteName,Departure,Destination")] Route route)
        //{
        //    var checkName = db.Routes.FirstOrDefault(b => b.RouteName == route.RouteName);
        //    if (checkName == null)
        //    {
        //        if (ModelState.IsValid)
        //        {
        //            db.Routes.Add(route);
        //            db.SaveChanges();
        //            return RedirectToAction("Index");
        //        }
        //    }
        //    else
        //    {
        //        ModelState.AddModelError("", "Tên tuyến đường đã tồn tại!!");
        //    }

        //    return View(route);
        //}

        //// GET: BusStationArea/Routes/Edit/5
        //public ActionResult Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Route route = db.Routes.Find(id);
        //    if (route == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(route);
        //}

        //// POST: BusStationArea/Routes/Edit/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit([Bind(Include = "RouteID,RouteName,Departure,Destination")] Route route)
        //{
        //    var checkName = db.Routes.FirstOrDefault(b => b.RouteName == route.RouteName && b.RouteID != route.RouteID);
        //    if (checkName == null)
        //    {
        //        if (ModelState.IsValid)
        //        {
        //            db.Entry(route).State = EntityState.Modified;
        //            db.SaveChanges();
        //            return RedirectToAction("Index");
        //        }
        //    }
        //    else
        //    {
        //        ModelState.AddModelError("", "Tên tuyến đường đã tồn tại!!");
        //    }

        //    return View(route);
        //}

        //public ActionResult Delete(int id)
        //{
        //    Route route = db.Routes.Find(id);
        //    db.Routes.Remove(route);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PBL3_MVC/Areas/BusStationArea/Views/Routes/Create.cshtml
@*@model PBL3_MVC.Data.Tables.Route

@{
    ViewBag.Title = "Tạo tuyến mới";
    Layout = "~/Areas/BusStationArea/Views/Shared/_BusStationLayout.cshtml";
}

<h2>Tạo tuyến mới</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.RouteName, "Tên tuyến", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RouteName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RouteName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Departure, "Điểm khởi hành", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Departure, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Departure, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Destination, "Điểm kết thúc", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Destination, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Destination, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Tạo tuyến mới" class="btn btn-success btn-default" style="margin:15px"/>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Trở lại danh sách Tuyến", "Index")
</div>*@

PBL3_MVC/Areas/BusStationArea/Views/Routes/Edit.cshtml
@*@model PBL3_MVC.Data.Tables.Route

@{
    ViewBag.Title = "Chỉnh sửa Tuyến";
    Layout = "~/Areas/BusStationArea/Views/Shared/_BusStationLayout.cshtml";
}

<h2>Chỉnh sửa tuyến</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.RouteID)

        <div class="form-group">
            @Html.LabelFor(model => model.RouteName, "Tên tuyến", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RouteName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RouteName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Departure, "Điểm khởi hành", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Departure, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Departure, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Destination, "Điểm kết thúc", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Destination, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Destination, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-success btn-default" style="margin:15px" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Trở lại danh sách Tuyến", "Index")
</div>*@

PBL3_MVC/Areas/BusStationArea/Views/Routes/Index.cshtml
@model IEnumerable<PBL3_MVC.Data.Tables.Route>

@{
    ViewBag.Title = "Danh sách tuyến";
    Layout = "~/Areas/BusStationArea/Views/Shared/_BusStationLayout.cshtml";
}

<h2>Danh sách tuyến</h2>

@*<p>
    @Html.ActionLink("Tạo tuyến mới", "Create", "Routes", new { area = "BusStationArea" }, new { @class = "btn btn-success" })
</p>*@
<table class="table">
    <tr>
        <th>
            Tên tuyến
        </th>
        <th>
            Điểm khởi hành
        </th>
        <th>
            Điểm kết thúc
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.RouteName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Departure.LocationName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Destination.LocationName)
        </td>
        @*<td>
            @Html.ActionLink("Chỉnh sửa", "Edit", new { id=item.RouteID }) |
            @Html.ActionLink("Xóa", "Delete", new { id=item.RouteID }, new { onclick = "return confirm('Bạn có chắc chắn muốn xóa không?');" })
        </td>*@
    </tr>
}

</table>